trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/azure-dev-cli-apps:latest

steps:
  # Step 1: Install .NET 8.0 Runtime for PowerShell compatibility
  - task: UseDotNet@2
    displayName: "Install .NET Core 8.0.0 Runtime"
    inputs:
      packageType: runtime
      version: 8.0.0
      
  # Step 1.1: Install .NET 9.0 Runtime for PowerShell compatibility
  - task: UseDotNet@2
    displayName: "Install .NET Core 9.0.0 Runtime"
    inputs:
      packageType: runtime
      version: 9.0.0

  # Step 2: Install .NET 9.0 SDK for application build
  - task: UseDotNet@2
    displayName: "Install .NET 9.0 SDK"
    inputs:
      packageType: sdk
      version: 9.0.x

  # Step 3: Configure AZD to Use Azure CLI Authentication
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: "Configure AZD to Use AZ CLI Authentication"

  # Step 4: Provision Infrastructure
  - task: AzureCLI@2
    displayName: "Provision Infrastructure"
    inputs:
      azureSubscription: rg-prod-observix-connection-managed-identity
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --environment prod-observix --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: 8037b670-1744-44ab-b27d-b8f7f4997a25
      AZURE_ENV_NAME: prod-observix
      AZURE_LOCATION: eastus

  # Step 5: Deploy Application
  - task: AzureCLI@2
    displayName: "Deploy Application"
    inputs:
      azureSubscription: rg-prod-observix-connection-managed-identity
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --environment prod-observix --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: 8037b670-1744-44ab-b27d-b8f7f4997a25
      AZURE_ENV_NAME: prod-observix
      AZURE_LOCATION: eastus
